backend:
  name: git-gateway
  branch: master

media_folder: "/assets/img" # Folder where user uploaded files should go
public_folder: "/assets/img"

collections: # A list of collections the CMS should be able to edit
  - label: "Home"
    name: "home"
    format: "json"
    files:
      - label: "Image Gallery"
        name: "image-gallery"
        file: "_data/gallery.json"
        fields:
          - label: "Gallery Images"
            name: "image"
            widget: "list"
            field: {label: Image, name: image, widget: image}